# application.yml
spring:
  application:
    name: Appointment-Service

  data:
    mongodb:
      uri: mongodb://localhost:27017/appointment-service
      # For production, use:
      # uri: mongodb://username:password@host:port/appointment-service

  # Enable MongoDB auditing for @CreatedDate and @LastModifiedDate
  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

server:
  port: 8083

# Service URLs for OpenFeign clients
app:
  services:
    user-service:
      url: http://localhost:8081
    property-service:
      url: http://localhost:8082

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    root: INFO
    com.example.appointmentservice: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG

# Security Configuration - Disable for now (you can enable later if needed)
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Feign configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic
        requestInterceptors:
          - com.example.appointmentservice.config.FeignRequestInterceptor
      user-service:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: full
      property-service:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: full

# Circuit breaker configuration (optional - requires spring-cloud-starter-circuitbreaker-resilience4j)
# resilience4j:
#   circuitbreaker:
#     instances:
#       user-service:
#         register-health-indicator: true
#         failure-rate-threshold: 50
#         minimum-number-of-calls: 5
#         automatic-transition-from-open-to-half-open-enabled: true
#         wait-duration-in-open-state: 5s
#         permitted-number-of-calls-in-half-open-state: 3
#         sliding-window-size: 10
#         sliding-window-type: count_based
#       property-service:
#         register-health-indicator: true
#         failure-rate-threshold: 50
#         minimum-number-of-calls: 5
#         automatic-transition-from-open-to-half-open-enabled: true
#         wait-duration-in-open-state: 5s
#         permitted-number-of-calls-in-half-open-state: 3
#         sliding-window-size: 10
#         sliding-window-type: count_based

---
# Alternative application.properties format (if you prefer properties over yml)

# Application Configuration
# spring.application.name=Appointment-Service
# server.port=8083

# MongoDB Configuration
# spring.data.mongodb.uri=mongodb://localhost:27017/appointment-service

# Service URLs
# app.services.user-service.url=http://localhost:8081
# app.services.property-service.url=http://localhost:8082

# Actuator Configuration
# management.endpoints.web.exposure.include=health,info,metrics
# management.endpoint.health.show-details=always

# Logging Configuration
# logging.level.root=INFO
# logging.level.com.example.appointmentservice=DEBUG
# logging.level.org.springframework.data.mongodb=DEBUG
# logging.level.org.springframework.cloud.openfeign=DEBUG

# Security Configuration
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Feign Configuration
# feign.client.config.default.connectTimeout=5000
# feign.client.config.default.readTimeout=10000
# feign.client.config.default.loggerLevel=basic